USE MeowMatch;

INSERT INTO Dificuldade (nome, num_cartas) VALUES ('Facil', 3);
INSERT INTO Dificuldade (nome, num_cartas) VALUES ('Medio', 6);
INSERT INTO Dificuldade (nome, num_cartas) VALUES ('Dificil', 9);
INSERT INTO Jogador (username, senha) VALUES ('AstroNinja42', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('QuantumPulse', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('ShadowRider9', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('MysticVortex', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('BlazePhoenix1', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('NeonDreamer', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('TurboZenith', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('EnigmaVoyager', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('CrystalEcho', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('VortexWhisper', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('CosmicFusion', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('RadiantGlimmer', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('ElectricEclipse', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('SilentSpecter', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('StellarGamer7', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('HyperNovaX', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('LunarWanderer', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('QuantumShifter', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('AuroraKnight', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('BlazeStorm13', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('PhantomQuasar', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('ZenithRogue', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('NebulaScribe', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('MysticForge', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('GalacticWraith', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('ThunderPulse', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('EclipseKnight', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('StarGlider', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('CelestialScribe', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('NeonPhantom', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('ArcticShade', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('InfernoSpecter', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('VortexRider', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('RadiantBlaze', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('CosmicEchoes', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('ShadowPulse', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('BlazeVoyager', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('QuantumLunar', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('StellarQuester', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('NebulaStorm', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('TitanGlimmer', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('EchoKnight', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('AuroraSpecter', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('CelestialVoyager', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('LunarFusion', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('SolarShifter', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('PhantomEcho', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('RadiantFlare', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('NeonEnigma', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('HyperGlider', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('AstroStorm', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('QuantumBlaze', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('VortexKnight', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('MysticNova', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('CelestialRider', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('ThunderEcho', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('StellarScribe', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('BlazeShade', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('RadiantPulse', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('CosmicVoyager', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('ShadowGlimmer', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('AuroraRogue', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('TitanStorm', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('NeonEclipse', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('HyperSpecter', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('LunarPhantom', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('EnigmaShifter', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('VortexBlaze', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('PhantomGlider', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('CelestialStorm', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('QuantumEcho', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('RadiantKnight', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('CosmicShade', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('StellarVoyager', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('BlazeSpecter', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('ThunderPulseX', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('LunarEchoes', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('AuroraRider', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('CelestialGlimmer', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('VortexFusion', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('ShadowEclipse', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('RadiantNova', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('PhantomVoyager', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('StellarShifter', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('QuantumSpecter', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('CosmicPulse', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('HyperStorm', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('AuroraBlaze', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('TitanEcho', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('LunarQuester', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('CelestialShifter', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('NeonGlimmer', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('VortexVoyager', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('RadiantSpecter', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('ShadowNova', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('BlazeFusion', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('CosmicRider', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('StellarEcho', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('QuantumPulseX', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Jogador (username, senha) VALUES ('AuroraSpecterX', '$2b$12$xPE.R/LHtecfFyQInFtDHOd1lqEuwwhUvGfB0Qmyf/i7Ceot4Lr1e.');
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000001_017.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000003_012.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000003_013.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000003_015.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000003_029.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000005_022.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000005_023.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000006_013.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000006_024.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000009_009.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000010_000.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000011_001.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000011_010.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000011_023.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000011_025.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000012_028.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000013_017.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000016_018.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000017_002.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000017_007.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000020_004.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000022_003.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000022_010.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000024_024.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000025_022.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000027_018.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000028_015.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000030_026.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000031_010.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000032_015.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000033_018.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000034_028.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000036_000.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000036_019.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000037_004.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000038_015.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000041_001.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000043_025.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000046_023.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000048_014.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000048_028.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000050_008.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000050_010.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000050_015.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000051_012.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000053_011.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000055_006.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000057_001.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000058_016.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000059_000.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000059_017.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000059_027.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000061_018.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000061_026.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000063_009.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000064_017.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000066_003.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000066_028.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000067_015.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000069_028.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000071_013.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000075_026.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000075_028.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000076_000.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000076_020.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000076_024.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000078_003.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000078_009.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000078_023.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000081_017.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000084_004.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000084_026.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000085_016.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000088_015.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000091_014.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000096_019.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000097_019.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000099_006.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000301_006.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000301_018.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000302_000.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000302_015.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000303_019.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000306_016.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000310_002.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000311_008.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000311_015.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000312_012.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000313_001.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000315_013.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000316_006.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000320_003.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000321_008.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000321_028.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000322_001.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000322_007.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000322_021.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000323_003.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000324_011.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000327_025.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000328_011.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000329_021.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000331_018.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000331_021.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000334_028.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000335_025.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000336_011.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000337_015.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000340_014.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000340_023.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000341_004.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000342_016.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000347_001.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000347_013.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000348_015.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000348_020.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000349_011.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000350_026.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000351_000.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000351_003.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000351_022.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000355_000.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000355_004.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000355_010.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000355_012.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000355_024.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000359_025.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000361_028.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000362_024.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000363_003.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000365_027.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000366_028.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000368_024.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000369_024.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000371_007.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000371_009.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000371_015.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000374_003.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000375_001.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000375_009.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000375_016.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000376_029.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000377_001.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000379_003.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000379_005.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000380_021.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000381_027.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000382_010.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000385_000.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000385_014.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000386_013.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000388_028.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000392_001.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000393_010.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000393_014.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000393_016.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000395_024.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000399_019.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000400_004.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000400_021.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000402_000.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000404_003.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000405_017.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000407_015.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000407_019.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000409_022.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000412_001.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000412_008.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000413_001.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000417_019.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000419_017.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000419_023.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000422_026.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000424_027.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000425_009.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000426_014.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000426_016.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000426_026.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000429_003.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000429_023.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000431_003.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000431_009.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000431_013.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000431_025.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000432_006.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000432_026.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000435_006.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000436_005.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000437_029.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000439_009.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000440_022.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000441_001.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000441_011.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000446_002.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000447_018.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000450_024.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000450_028.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000451_021.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000452_003.jpg'));
INSERT INTO Cartas (imagem) VALUES (LOAD_FILE('/var/lib/mysql-files/Random_Images/00000452_011.jpg'));
